<?php return array (
  'db_server' => 'localhost',
  'db_user' => 'root',
  'db_password' => 'root',
  'db_database' => 'tooltest',
  'replace_usernames' => 'n',
  'replace_hashtags' => 'n',
  'replace_links' => 'n',
  'end_time' => 1379658842,
  'start_time' => 1379658782,
  'keywords' => 'nokia',
  'pid' => 5820,
  'TWITTER_CONSUMER_KEY' => '',
  'TWITTER_CONSUMER_SECRET' => '',
  'CONSUMER_KEY' => '',
  'CONSUMER_SECRET' => '',
  'OAUTH_TOKEN' => '',
  'OAUTH_SECRET' => '',
) ;
