<?php return array (
  'db_server' => '',
  'db_user' => '',
  'db_password' => '',
  'db_database' => '',
  'replace_usernames' => '',
  'replace_hashtags' => '',
  'replace_links' => '',
  'end_time' => ,
  'start_time' => ,
  'keywords' => '',
  'pid' => ,
  'TWITTER_CONSUMER_KEY' => '',
  'TWITTER_CONSUMER_SECRET' => '',
  'CONSUMER_KEY' => '',
  'CONSUMER_SECRET' => '',
  'OAUTH_TOKEN' => '',
  'OAUTH_SECRET' => '',
) ;
